# Generated by Django 3.2.8 on 2024-04-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_articlecomment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Blog Article', 'verbose_name_plural': "Blog Article's"},
        ),
    ]
