# Generated by Django 3.2.8 on 2024-04-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={},
        ),
    ]
